// API v1 response types — re-exported (type-only) from the shared contract
// package @rdoc-suite/fleetplanner-contracts, the single source of truth for
// both the backend and this SPA. Type-only, so zod is never bundled here.
export type {
  ApiError as ApiErrorBody,
  SessionUser,
  SessionResponse,
  OperationSummary,
  OrgFleetResponse,
  OrgFleetEntry,
  Seat,
  FleetUnit,
  ResourceLink,
  OperationStream,
  OperationDetail,
  ShipSummary,
  OperatorView,
  TemplateSummary,
  RoadmapItem,
  GuildSettings,
  GuildSettingsMember,
  GuildSettingsResponse,
  NeedsResponse,
  ShipNeed,
  Partnership,
  IncomingDistribution,
  PartnershipsResponse,
  FleetImportResponse,
  AdminGuild,
  AdminGuildsResponse,
  AdminUser,
  AdminUsersResponse,
  AdminSettingsResponse,
  SystemHealthResponse,
  ServiceHealth,
  SyncHealth,
  OperationsMetric,
  GuildEventsMetric,
  SystemEvent,
  SystemEventsResponse,
  AccountResponse,
  DiagnosticsResponse,
  PollSummary,
  PollDetail,
  PollOptionResult,
  PollListResponse,
  CreatePollRequest,
  UpdatePollRequest,
  UpdatePollOption,
} from "@rdoc-suite/fleetplanner-contracts";

// The error code union is referenced directly by the client; mirror it from
// the ApiError contract shape.
export type ApiErrorCode = import("@rdoc-suite/fleetplanner-contracts").ApiError["error"]["code"];
